[window]
startup_mode = "Maximized"
decorations = "None"
opacity = 0.95

[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
size = 10.5

[font.offset]
x = -1
y = 1

[cursor]
style = { shape = "Beam", blinking = "Never" }
vi_mode_style = { shape = "Block", blinking = "Never" }

[mouse]
hide_when_typing = true

[env]
TERM = "xterm-256color"
