#!/bin/sh
workspaces() {
ws1="1"
ws2="2"
ws3="3"
ws4="4"
ws5="5"
ws6="6"

un="w0"

# check if Occupied
currw=$(hyprctl activewindow | grep "workspace: " | cut -d' ' -f2)
o1=$(echo "$currw" | grep "$ws1")
o2=$(echo "$currw" | grep "$ws2")
o3=$(echo "$currw" | grep "$ws3")
o4=$(echo "$currw" | grep "$ws4")
o5=$(echo "$currw" | grep "$ws5")
o6=$(echo "$currw" | grep "$ws6")

ic_1=""
ic_2=""
ic_3=""
ic_4=""
ic_5=""
ic_6=""
if [ $o1 ]; then
    ic_1=""
elif [ $o2 ]; then
    ic_2=""
elif [ $o3 ]; then
    ic_3=""
elif [ $o4 ]; then
    ic_4=""
elif [ $o5 ]; then
    ic_5=""
elif [ $o6 ]; then
    ic_6=""
fi

echo "(box	:class \"works\"	:orientation \"h\" :spacing 5 :space-evenly \"false\" (button :onclick \"hyprctl dispatch workspace $ws1\"	:class	\"$un$o1$f1\"	\"$ic_1\") (button :onclick \"hyprctl dispatch workspace $ws2\"	:class \"$un$o2$f2\"	 \"$ic_2\") (button :onclick \"hyprctl dispatch workspace $ws3\"	:class \"$un$o3$f3\" \"$ic_3\") (button :onclick \"hyprctl dispatch workspace $ws4\"	:class \"$un$o4$f4\"	\"$ic_4\") (button :onclick \"hyprctl dispatch workspace $ws5\"	:class \"$un$o5$f5\" \"$ic_5\")  (button :onclick \"hyprctl dispatch workspace $ws6\"	:class \"$un$o6$f6\" \"$ic_6\"))"

}
workspaces
