set -gx XDG_CONFIG_HOME "$HOME/.config"
set -gx XDG_CURRENT_DESKTOP "GNOME"
set -gx EDITOR "nvim"
set -gx EMULATOR "alacritty"
set -gx BROWSER "zen-browser"
set -gx WINDOWMANAGER "Hyprland"
set -gx FILEMANAGER "thunar"
set -gx LAUNCHER "fuzzel"

set -a PATH "$HOME/.local/bin"
set -a PATH "$HOME/.cargo/bin"
